from __future__ import annotations

import argparse
import sys

from . import gitio, prompts
from .providers import (
    APIError,
    DEFAULT_OLLAMA_NUM_CTX,
    PROVIDERS,
    UnknownProvider,
    chat,
    resolve_config,
    strip_fences,
)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="qwen-commit",
        description="Suggest a commit message for the staged diff, generated by a local Qwen model.",
    )
    parser.add_argument("--commit", action="store_true", help="Commit the staged changes with the generated message.")
    parser.add_argument("--install-hook", action="store_true", help="Install a prepare-commit-msg hook that prefills the editor.")
    parser.add_argument("--style", choices=sorted(prompts.STYLE_SPECS), default="conventional")
    parser.add_argument("--max-diff-chars", type=int, default=12000, help="Per-invocation diff budget; larger diffs are truncated per file.")
    parser.add_argument("--log-lines", type=int, default=10, help="How many recent commits to show the model for style mimicry.")
    parser.add_argument("--provider", choices=sorted(PROVIDERS), default=None, help="Endpoint preset: dashscope (default), modelscope, or ollama (local).")
    parser.add_argument("--model", default=None)
    parser.add_argument("--base-url", default=None)
    parser.add_argument("--api-key", default=None)
    parser.add_argument("--num-ctx", type=int, default=None, help="Ollama context size (default 8192 for the ollama provider).")
    parser.add_argument("--timeout", type=float, default=120.0)
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)

    if args.install_hook:
        try:
            hook = gitio.install_hook()
        except gitio.GitError as exc:
            print(f"error: {exc}", file=sys.stderr)
            return 2
        print(f"installed prepare-commit-msg hook at {hook}")
        return 0

    try:
        diff = gitio.staged_diff()
    except gitio.GitError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2
    if not diff.strip():
        print("error: nothing staged; run git add first", file=sys.stderr)
        return 2

    system, user = prompts.build_messages(
        args.style, gitio.truncate_diff(diff, args.max_diff_chars), gitio.recent_log(args.log_lines)
    )

    try:
        provider, base_url, model, api_key = resolve_config(
            provider=args.provider,
            base_url=args.base_url,
            model=args.model,
            api_key=args.api_key,
        )
    except UnknownProvider as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2
    num_ctx = args.num_ctx
    if num_ctx is None and provider == "ollama":
        num_ctx = DEFAULT_OLLAMA_NUM_CTX
    options = {"num_ctx": num_ctx} if num_ctx else None

    try:
        message = chat(
            base_url=base_url,
            api_key=api_key,
            model=model,
            system=system,
            user=user,
            timeout=args.timeout,
            options=options,
            wire="ollama" if provider == "ollama" else "openai",
        )
    except APIError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1
    message = strip_fences(message)
    if not message:
        print("error: model returned an empty message", file=sys.stderr)
        return 1
    print(message)

    if args.commit:
        try:
            gitio.commit_with(message)
        except gitio.GitError as exc:
            print(f"error: {exc}", file=sys.stderr)
            return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
